// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIeEmGac3QS25As7M6HurS-khWDvNV86A',
    appId: '1:683149920474:web:01622f002cd74b8147fde3',
    messagingSenderId: '683149920474',
    projectId: 'student-reg-fcaf3',
    authDomain: 'student-reg-fcaf3.firebaseapp.com',
    storageBucket: 'student-reg-fcaf3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJZRNZcdeLGzLYuD1EkSqVMm1-dQMnLCo',
    appId: '1:683149920474:android:fefb089c38e425e647fde3',
    messagingSenderId: '683149920474',
    projectId: 'student-reg-fcaf3',
    storageBucket: 'student-reg-fcaf3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0TiiMDTmBmhXdUBr7U1iJm5bXh8ZgIfg',
    appId: '1:683149920474:ios:be199b20d7d0c80947fde3',
    messagingSenderId: '683149920474',
    projectId: 'student-reg-fcaf3',
    storageBucket: 'student-reg-fcaf3.appspot.com',
    iosClientId: '683149920474-980j3aqvk599h89s3v2tv253klhtgrbn.apps.googleusercontent.com',
    iosBundleId: 'com.example.studentRegisterationSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0TiiMDTmBmhXdUBr7U1iJm5bXh8ZgIfg',
    appId: '1:683149920474:ios:be199b20d7d0c80947fde3',
    messagingSenderId: '683149920474',
    projectId: 'student-reg-fcaf3',
    storageBucket: 'student-reg-fcaf3.appspot.com',
    iosClientId: '683149920474-980j3aqvk599h89s3v2tv253klhtgrbn.apps.googleusercontent.com',
    iosBundleId: 'com.example.studentRegisterationSystem',
  );
}
